EVG-8963: implement test results gRPC client
evergreen-ci/timber pull request #45
Opened 2020-09-10 19:41 UTC by Kimchelly

JIRA: https://jira.mongodb.org/browse/EVG-8963

Also some minor linter fixes.

2020-09-10 20:03 UTC, julianedwards requested changes
Can we move the types and export functions out of `client.go` and into a separate file?

2020-09-10 20:03 UTC, julianedwards commented on testresults/client.go
> +// Export converts a Result into the equivalent protobuf TestResult.
`Export` -> `export`

2020-09-10 20:03 UTC, julianedwards commented on testutil/server.go
> +// on the port and url from the specified dial options
missing period

2020-09-10 20:20 UTC, Kimchelly reviewed
I moved the types to separate files and did the same thing for system metrics.

2020-09-10 20:20 UTC, Kimchelly commented on testresults/client.go
> +type CreateOptions struct {
Done.

2020-09-10 20:20 UTC, Kimchelly commented on testresults/client.go
> +}
I don't think so, but I copied these fields from system metrics, which seems to have copied it from buildlogger. Though, I don't really see why buildlogger needs them either. I removed them from system metrics and test results, but not buildlogger.

2020-09-10 20:20 UTC, Kimchelly commented on testresults/client.go
> +// Export converts a Result into the equivalent protobuf TestResult.
Done.

2020-09-10 20:20 UTC, Kimchelly commented on testutil/server.go
> +// on the port and url from the specified dial options
Fixed.

2020-09-11 13:37 UTC, julianedwards approved these changes

2020-09-11 14:46 UTC, merged